# Generated by Django 4.2.30 on 2026-06-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_shipping_carrier_order_tracking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='infill',
            field=models.CharField(default='20%', max_length=50),
        ),
    ]
