# Generated by Django 4.2.30 on 2026-06-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_request_infill'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='brand',
            field=models.CharField(blank=True, default='Generic', max_length=100, null=True),
        ),
    ]
